/*
 * Snap Conversions API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.snap.business.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.snap.business.sdk.JSON;

/**
 * CapiEvent
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class CapiEvent implements CapiEventExt<CapiEvent> {
  public static final String SERIALIZED_NAME_PIXEL_ID = "pixel_id";
  @SerializedName(SERIALIZED_NAME_PIXEL_ID)
  private String pixelId;

  public static final String SERIALIZED_NAME_APP_ID = "app_id";
  @SerializedName(SERIALIZED_NAME_APP_ID)
  private String appId;

  public static final String SERIALIZED_NAME_SNAP_APP_ID = "snap_app_id";
  @SerializedName(SERIALIZED_NAME_SNAP_APP_ID)
  private String snapAppId;

  public static final String SERIALIZED_NAME_EVENT_TYPE = "event_type";
  @SerializedName(SERIALIZED_NAME_EVENT_TYPE)
  private String eventType;

  public static final String SERIALIZED_NAME_EVENT_CONVERSION_TYPE = "event_conversion_type";
  @SerializedName(SERIALIZED_NAME_EVENT_CONVERSION_TYPE)
  private String eventConversionType;

  public static final String SERIALIZED_NAME_EVENT_TAG = "event_tag";
  @SerializedName(SERIALIZED_NAME_EVENT_TAG)
  private String eventTag;

  public static final String SERIALIZED_NAME_TIMESTAMP = "timestamp";
  @SerializedName(SERIALIZED_NAME_TIMESTAMP)
  private String timestamp;

  public static final String SERIALIZED_NAME_HASHED_EMAIL = "hashed_email";
  @SerializedName(SERIALIZED_NAME_HASHED_EMAIL)
  private String hashedEmail;

  public static final String SERIALIZED_NAME_HASHED_MOBILE_AD_ID = "hashed_mobile_ad_id";
  @SerializedName(SERIALIZED_NAME_HASHED_MOBILE_AD_ID)
  private String hashedMobileAdId;

  public static final String SERIALIZED_NAME_UUID_C1 = "uuid_c1";
  @SerializedName(SERIALIZED_NAME_UUID_C1)
  private String uuidC1;

  public static final String SERIALIZED_NAME_HASHED_IDFV = "hashed_idfv";
  @SerializedName(SERIALIZED_NAME_HASHED_IDFV)
  private String hashedIdfv;

  public static final String SERIALIZED_NAME_HASHED_PHONE_NUMBER = "hashed_phone_number";
  @SerializedName(SERIALIZED_NAME_HASHED_PHONE_NUMBER)
  private String hashedPhoneNumber;

  public static final String SERIALIZED_NAME_USER_AGENT = "user_agent";
  @SerializedName(SERIALIZED_NAME_USER_AGENT)
  private String userAgent;

  public static final String SERIALIZED_NAME_HASHED_IP_ADDRESS = "hashed_ip_address";
  @SerializedName(SERIALIZED_NAME_HASHED_IP_ADDRESS)
  private String hashedIpAddress;

  public static final String SERIALIZED_NAME_ITEM_CATEGORY = "item_category";
  @SerializedName(SERIALIZED_NAME_ITEM_CATEGORY)
  private String itemCategory;

  public static final String SERIALIZED_NAME_ITEM_IDS = "item_ids";
  @SerializedName(SERIALIZED_NAME_ITEM_IDS)
  private String itemIds;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  public static final String SERIALIZED_NAME_NUMBER_ITEMS = "number_items";
  @SerializedName(SERIALIZED_NAME_NUMBER_ITEMS)
  private String numberItems;

  public static final String SERIALIZED_NAME_PRICE = "price";
  @SerializedName(SERIALIZED_NAME_PRICE)
  private String price;

  public static final String SERIALIZED_NAME_CURRENCY = "currency";
  @SerializedName(SERIALIZED_NAME_CURRENCY)
  private String currency;

  public static final String SERIALIZED_NAME_TRANSACTION_ID = "transaction_id";
  @SerializedName(SERIALIZED_NAME_TRANSACTION_ID)
  private String transactionId;

  public static final String SERIALIZED_NAME_LEVEL = "level";
  @SerializedName(SERIALIZED_NAME_LEVEL)
  private String level;

  public static final String SERIALIZED_NAME_CLIENT_DEDUP_ID = "client_dedup_id";
  @SerializedName(SERIALIZED_NAME_CLIENT_DEDUP_ID)
  private String clientDedupId;

  public static final String SERIALIZED_NAME_DATA_USE = "data_use";
  @SerializedName(SERIALIZED_NAME_DATA_USE)
  private String dataUse;

  public static final String SERIALIZED_NAME_SEARCH_STRING = "search_string";
  @SerializedName(SERIALIZED_NAME_SEARCH_STRING)
  private String searchString;

  public static final String SERIALIZED_NAME_PAGE_URL = "page_url";
  @SerializedName(SERIALIZED_NAME_PAGE_URL)
  private String pageUrl;

  public static final String SERIALIZED_NAME_SIGN_UP_METHOD = "sign_up_method";
  @SerializedName(SERIALIZED_NAME_SIGN_UP_METHOD)
  private String signUpMethod;

  public static final String SERIALIZED_NAME_HASHED_FIRST_NAME_SHA = "hashed_first_name_sha";
  @SerializedName(SERIALIZED_NAME_HASHED_FIRST_NAME_SHA)
  private String hashedFirstNameSha;

  public static final String SERIALIZED_NAME_HASHED_FIRST_NAME_SDX = "hashed_first_name_sdx";
  @SerializedName(SERIALIZED_NAME_HASHED_FIRST_NAME_SDX)
  private String hashedFirstNameSdx;

  public static final String SERIALIZED_NAME_HASHED_MIDDLE_NAME_SHA = "hashed_middle_name_sha";
  @SerializedName(SERIALIZED_NAME_HASHED_MIDDLE_NAME_SHA)
  private String hashedMiddleNameSha;

  public static final String SERIALIZED_NAME_HASHED_MIDDLE_NAME_SDX = "hashed_middle_name_sdx";
  @SerializedName(SERIALIZED_NAME_HASHED_MIDDLE_NAME_SDX)
  private String hashedMiddleNameSdx;

  public static final String SERIALIZED_NAME_HASHED_LAST_NAME_SHA = "hashed_last_name_sha";
  @SerializedName(SERIALIZED_NAME_HASHED_LAST_NAME_SHA)
  private String hashedLastNameSha;

  public static final String SERIALIZED_NAME_HASHED_LAST_NAME_SDX = "hashed_last_name_sdx";
  @SerializedName(SERIALIZED_NAME_HASHED_LAST_NAME_SDX)
  private String hashedLastNameSdx;

  public static final String SERIALIZED_NAME_HASHED_CITY_SHA = "hashed_city_sha";
  @SerializedName(SERIALIZED_NAME_HASHED_CITY_SHA)
  private String hashedCitySha;

  public static final String SERIALIZED_NAME_HASHED_CITY_SDX = "hashed_city_sdx";
  @SerializedName(SERIALIZED_NAME_HASHED_CITY_SDX)
  private String hashedCitySdx;

  public static final String SERIALIZED_NAME_HASHED_STATE_SHA = "hashed_state_sha";
  @SerializedName(SERIALIZED_NAME_HASHED_STATE_SHA)
  private String hashedStateSha;

  public static final String SERIALIZED_NAME_HASHED_STATE_SDX = "hashed_state_sdx";
  @SerializedName(SERIALIZED_NAME_HASHED_STATE_SDX)
  private String hashedStateSdx;

  public static final String SERIALIZED_NAME_HASHED_ZIP = "hashed_zip";
  @SerializedName(SERIALIZED_NAME_HASHED_ZIP)
  private String hashedZip;

  public static final String SERIALIZED_NAME_HASHED_DOB_MONTH = "hashed_dob_month";
  @SerializedName(SERIALIZED_NAME_HASHED_DOB_MONTH)
  private String hashedDobMonth;

  public static final String SERIALIZED_NAME_HASHED_DOB_DAY = "hashed_dob_day";
  @SerializedName(SERIALIZED_NAME_HASHED_DOB_DAY)
  private String hashedDobDay;

  public static final String SERIALIZED_NAME_INTEGRATION = "integration";
  @SerializedName(SERIALIZED_NAME_INTEGRATION)
  private String integration;

  public static final String SERIALIZED_NAME_CLICK_ID = "click_id";
  @SerializedName(SERIALIZED_NAME_CLICK_ID)
  private String clickId;

  public static final String SERIALIZED_NAME_BRANDS = "brands";
  @SerializedName(SERIALIZED_NAME_BRANDS)
  private String brands;

  public static final String SERIALIZED_NAME_COUNTRY = "country";
  @SerializedName(SERIALIZED_NAME_COUNTRY)
  private String country;

  public static final String SERIALIZED_NAME_REGION = "region";
  @SerializedName(SERIALIZED_NAME_REGION)
  private String region;

  public static final String SERIALIZED_NAME_PURCHASE_USER_VALUE = "purchase_user_value";
  @SerializedName(SERIALIZED_NAME_PURCHASE_USER_VALUE)
  private String purchaseUserValue;

  public CapiEvent() { 
  }

  public CapiEvent pixelId(String pixelId) {
    
    this.pixelId = pixelId;
    return this;
  }

   /**
   * Get pixelId
   * @return pixelId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getPixelId() {
    return pixelId;
  }


  public void setPixelId(String pixelId) {
    this.pixelId = pixelId;
  }


  public CapiEvent appId(String appId) {
    
    this.appId = appId;
    return this;
  }

   /**
   * Get appId
   * @return appId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getAppId() {
    return appId;
  }


  public void setAppId(String appId) {
    this.appId = appId;
  }


  public CapiEvent snapAppId(String snapAppId) {
    
    this.snapAppId = snapAppId;
    return this;
  }

   /**
   * Get snapAppId
   * @return snapAppId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getSnapAppId() {
    return snapAppId;
  }


  public void setSnapAppId(String snapAppId) {
    this.snapAppId = snapAppId;
  }


  public CapiEvent eventType(String eventType) {
    
    this.eventType = eventType;
    return this;
  }

   /**
   * Get eventType
   * @return eventType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getEventType() {
    return eventType;
  }


  public void setEventType(String eventType) {
    this.eventType = eventType;
  }


  public CapiEvent eventConversionType(String eventConversionType) {
    
    this.eventConversionType = eventConversionType;
    return this;
  }

   /**
   * Get eventConversionType
   * @return eventConversionType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getEventConversionType() {
    return eventConversionType;
  }


  public void setEventConversionType(String eventConversionType) {
    this.eventConversionType = eventConversionType;
  }


  public CapiEvent eventTag(String eventTag) {
    
    this.eventTag = eventTag;
    return this;
  }

   /**
   * Get eventTag
   * @return eventTag
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getEventTag() {
    return eventTag;
  }


  public void setEventTag(String eventTag) {
    this.eventTag = eventTag;
  }


  public CapiEvent timestamp(String timestamp) {
    
    this.timestamp = timestamp;
    return this;
  }

   /**
   * Get timestamp
   * @return timestamp
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getTimestamp() {
    return timestamp;
  }


  public void setTimestamp(String timestamp) {
    this.timestamp = timestamp;
  }


  public CapiEvent hashedEmail(String hashedEmail) {
    
    this.hashedEmail = hashedEmail;
    return this;
  }

   /**
   * Get hashedEmail
   * @return hashedEmail
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getHashedEmail() {
    return hashedEmail;
  }


  public void setHashedEmail(String hashedEmail) {
    this.hashedEmail = hashedEmail;
  }


  public CapiEvent hashedMobileAdId(String hashedMobileAdId) {
    
    this.hashedMobileAdId = hashedMobileAdId;
    return this;
  }

   /**
   * Get hashedMobileAdId
   * @return hashedMobileAdId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getHashedMobileAdId() {
    return hashedMobileAdId;
  }


  public void setHashedMobileAdId(String hashedMobileAdId) {
    this.hashedMobileAdId = hashedMobileAdId;
  }


  public CapiEvent uuidC1(String uuidC1) {
    
    this.uuidC1 = uuidC1;
    return this;
  }

   /**
   * Get uuidC1
   * @return uuidC1
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getUuidC1() {
    return uuidC1;
  }


  public void setUuidC1(String uuidC1) {
    this.uuidC1 = uuidC1;
  }


  public CapiEvent hashedIdfv(String hashedIdfv) {
    
    this.hashedIdfv = hashedIdfv;
    return this;
  }

   /**
   * Get hashedIdfv
   * @return hashedIdfv
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getHashedIdfv() {
    return hashedIdfv;
  }


  public void setHashedIdfv(String hashedIdfv) {
    this.hashedIdfv = hashedIdfv;
  }


  public CapiEvent hashedPhoneNumber(String hashedPhoneNumber) {
    
    this.hashedPhoneNumber = hashedPhoneNumber;
    return this;
  }

   /**
   * Get hashedPhoneNumber
   * @return hashedPhoneNumber
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getHashedPhoneNumber() {
    return hashedPhoneNumber;
  }


  public void setHashedPhoneNumber(String hashedPhoneNumber) {
    this.hashedPhoneNumber = hashedPhoneNumber;
  }


  public CapiEvent userAgent(String userAgent) {
    
    this.userAgent = userAgent;
    return this;
  }

   /**
   * Get userAgent
   * @return userAgent
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getUserAgent() {
    return userAgent;
  }


  public void setUserAgent(String userAgent) {
    this.userAgent = userAgent;
  }


  public CapiEvent hashedIpAddress(String hashedIpAddress) {
    
    this.hashedIpAddress = hashedIpAddress;
    return this;
  }

   /**
   * Get hashedIpAddress
   * @return hashedIpAddress
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getHashedIpAddress() {
    return hashedIpAddress;
  }


  public void setHashedIpAddress(String hashedIpAddress) {
    this.hashedIpAddress = hashedIpAddress;
  }


  public CapiEvent itemCategory(String itemCategory) {
    
    this.itemCategory = itemCategory;
    return this;
  }

   /**
   * Get itemCategory
   * @return itemCategory
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getItemCategory() {
    return itemCategory;
  }


  public void setItemCategory(String itemCategory) {
    this.itemCategory = itemCategory;
  }


  public CapiEvent itemIds(String itemIds) {
    
    this.itemIds = itemIds;
    return this;
  }

   /**
   * Get itemIds
   * @return itemIds
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getItemIds() {
    return itemIds;
  }


  public void setItemIds(String itemIds) {
    this.itemIds = itemIds;
  }


  public CapiEvent description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    this.description = description;
  }


  public CapiEvent numberItems(String numberItems) {
    
    this.numberItems = numberItems;
    return this;
  }

   /**
   * Get numberItems
   * @return numberItems
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getNumberItems() {
    return numberItems;
  }


  public void setNumberItems(String numberItems) {
    this.numberItems = numberItems;
  }


  public CapiEvent price(String price) {
    
    this.price = price;
    return this;
  }

   /**
   * Get price
   * @return price
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getPrice() {
    return price;
  }


  public void setPrice(String price) {
    this.price = price;
  }


  public CapiEvent currency(String currency) {
    
    this.currency = currency;
    return this;
  }

   /**
   * Get currency
   * @return currency
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getCurrency() {
    return currency;
  }


  public void setCurrency(String currency) {
    this.currency = currency;
  }


  public CapiEvent transactionId(String transactionId) {
    
    this.transactionId = transactionId;
    return this;
  }

   /**
   * Get transactionId
   * @return transactionId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getTransactionId() {
    return transactionId;
  }


  public void setTransactionId(String transactionId) {
    this.transactionId = transactionId;
  }


  public CapiEvent level(String level) {
    
    this.level = level;
    return this;
  }

   /**
   * Get level
   * @return level
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getLevel() {
    return level;
  }


  public void setLevel(String level) {
    this.level = level;
  }


  public CapiEvent clientDedupId(String clientDedupId) {
    
    this.clientDedupId = clientDedupId;
    return this;
  }

   /**
   * Get clientDedupId
   * @return clientDedupId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getClientDedupId() {
    return clientDedupId;
  }


  public void setClientDedupId(String clientDedupId) {
    this.clientDedupId = clientDedupId;
  }


  public CapiEvent dataUse(String dataUse) {
    
    this.dataUse = dataUse;
    return this;
  }

   /**
   * Get dataUse
   * @return dataUse
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getDataUse() {
    return dataUse;
  }


  public void setDataUse(String dataUse) {
    this.dataUse = dataUse;
  }


  public CapiEvent searchString(String searchString) {
    
    this.searchString = searchString;
    return this;
  }

   /**
   * Get searchString
   * @return searchString
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getSearchString() {
    return searchString;
  }


  public void setSearchString(String searchString) {
    this.searchString = searchString;
  }


  public CapiEvent pageUrl(String pageUrl) {
    
    this.pageUrl = pageUrl;
    return this;
  }

   /**
   * Get pageUrl
   * @return pageUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getPageUrl() {
    return pageUrl;
  }


  public void setPageUrl(String pageUrl) {
    this.pageUrl = pageUrl;
  }


  public CapiEvent signUpMethod(String signUpMethod) {
    
    this.signUpMethod = signUpMethod;
    return this;
  }

   /**
   * Get signUpMethod
   * @return signUpMethod
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getSignUpMethod() {
    return signUpMethod;
  }


  public void setSignUpMethod(String signUpMethod) {
    this.signUpMethod = signUpMethod;
  }


  public CapiEvent hashedFirstNameSha(String hashedFirstNameSha) {
    
    this.hashedFirstNameSha = hashedFirstNameSha;
    return this;
  }

   /**
   * Get hashedFirstNameSha
   * @return hashedFirstNameSha
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getHashedFirstNameSha() {
    return hashedFirstNameSha;
  }


  public void setHashedFirstNameSha(String hashedFirstNameSha) {
    this.hashedFirstNameSha = hashedFirstNameSha;
  }


  public CapiEvent hashedFirstNameSdx(String hashedFirstNameSdx) {
    
    this.hashedFirstNameSdx = hashedFirstNameSdx;
    return this;
  }

   /**
   * Get hashedFirstNameSdx
   * @return hashedFirstNameSdx
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getHashedFirstNameSdx() {
    return hashedFirstNameSdx;
  }


  public void setHashedFirstNameSdx(String hashedFirstNameSdx) {
    this.hashedFirstNameSdx = hashedFirstNameSdx;
  }


  public CapiEvent hashedMiddleNameSha(String hashedMiddleNameSha) {
    
    this.hashedMiddleNameSha = hashedMiddleNameSha;
    return this;
  }

   /**
   * Get hashedMiddleNameSha
   * @return hashedMiddleNameSha
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getHashedMiddleNameSha() {
    return hashedMiddleNameSha;
  }


  public void setHashedMiddleNameSha(String hashedMiddleNameSha) {
    this.hashedMiddleNameSha = hashedMiddleNameSha;
  }


  public CapiEvent hashedMiddleNameSdx(String hashedMiddleNameSdx) {
    
    this.hashedMiddleNameSdx = hashedMiddleNameSdx;
    return this;
  }

   /**
   * Get hashedMiddleNameSdx
   * @return hashedMiddleNameSdx
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getHashedMiddleNameSdx() {
    return hashedMiddleNameSdx;
  }


  public void setHashedMiddleNameSdx(String hashedMiddleNameSdx) {
    this.hashedMiddleNameSdx = hashedMiddleNameSdx;
  }


  public CapiEvent hashedLastNameSha(String hashedLastNameSha) {
    
    this.hashedLastNameSha = hashedLastNameSha;
    return this;
  }

   /**
   * Get hashedLastNameSha
   * @return hashedLastNameSha
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getHashedLastNameSha() {
    return hashedLastNameSha;
  }


  public void setHashedLastNameSha(String hashedLastNameSha) {
    this.hashedLastNameSha = hashedLastNameSha;
  }


  public CapiEvent hashedLastNameSdx(String hashedLastNameSdx) {
    
    this.hashedLastNameSdx = hashedLastNameSdx;
    return this;
  }

   /**
   * Get hashedLastNameSdx
   * @return hashedLastNameSdx
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getHashedLastNameSdx() {
    return hashedLastNameSdx;
  }


  public void setHashedLastNameSdx(String hashedLastNameSdx) {
    this.hashedLastNameSdx = hashedLastNameSdx;
  }


  public CapiEvent hashedCitySha(String hashedCitySha) {
    
    this.hashedCitySha = hashedCitySha;
    return this;
  }

   /**
   * Get hashedCitySha
   * @return hashedCitySha
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getHashedCitySha() {
    return hashedCitySha;
  }


  public void setHashedCitySha(String hashedCitySha) {
    this.hashedCitySha = hashedCitySha;
  }


  public CapiEvent hashedCitySdx(String hashedCitySdx) {
    
    this.hashedCitySdx = hashedCitySdx;
    return this;
  }

   /**
   * Get hashedCitySdx
   * @return hashedCitySdx
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getHashedCitySdx() {
    return hashedCitySdx;
  }


  public void setHashedCitySdx(String hashedCitySdx) {
    this.hashedCitySdx = hashedCitySdx;
  }


  public CapiEvent hashedStateSha(String hashedStateSha) {
    
    this.hashedStateSha = hashedStateSha;
    return this;
  }

   /**
   * Get hashedStateSha
   * @return hashedStateSha
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getHashedStateSha() {
    return hashedStateSha;
  }


  public void setHashedStateSha(String hashedStateSha) {
    this.hashedStateSha = hashedStateSha;
  }


  public CapiEvent hashedStateSdx(String hashedStateSdx) {
    
    this.hashedStateSdx = hashedStateSdx;
    return this;
  }

   /**
   * Get hashedStateSdx
   * @return hashedStateSdx
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getHashedStateSdx() {
    return hashedStateSdx;
  }


  public void setHashedStateSdx(String hashedStateSdx) {
    this.hashedStateSdx = hashedStateSdx;
  }


  public CapiEvent hashedZip(String hashedZip) {
    
    this.hashedZip = hashedZip;
    return this;
  }

   /**
   * Get hashedZip
   * @return hashedZip
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getHashedZip() {
    return hashedZip;
  }


  public void setHashedZip(String hashedZip) {
    this.hashedZip = hashedZip;
  }


  public CapiEvent hashedDobMonth(String hashedDobMonth) {
    
    this.hashedDobMonth = hashedDobMonth;
    return this;
  }

   /**
   * Get hashedDobMonth
   * @return hashedDobMonth
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getHashedDobMonth() {
    return hashedDobMonth;
  }


  public void setHashedDobMonth(String hashedDobMonth) {
    this.hashedDobMonth = hashedDobMonth;
  }


  public CapiEvent hashedDobDay(String hashedDobDay) {
    
    this.hashedDobDay = hashedDobDay;
    return this;
  }

   /**
   * Get hashedDobDay
   * @return hashedDobDay
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getHashedDobDay() {
    return hashedDobDay;
  }


  public void setHashedDobDay(String hashedDobDay) {
    this.hashedDobDay = hashedDobDay;
  }


  public CapiEvent integration(String integration) {
    
    this.integration = integration;
    return this;
  }

   /**
   * Get integration
   * @return integration
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getIntegration() {
    return integration;
  }


  public void setIntegration(String integration) {
    this.integration = integration;
  }


  public CapiEvent clickId(String clickId) {
    
    this.clickId = clickId;
    return this;
  }

   /**
   * Get clickId
   * @return clickId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getClickId() {
    return clickId;
  }


  public void setClickId(String clickId) {
    this.clickId = clickId;
  }


  public CapiEvent brands(String brands) {
    
    this.brands = brands;
    return this;
  }

   /**
   * Get brands
   * @return brands
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getBrands() {
    return brands;
  }


  public void setBrands(String brands) {
    this.brands = brands;
  }


  public CapiEvent country(String country) {
    
    this.country = country;
    return this;
  }

   /**
   * Get country
   * @return country
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getCountry() {
    return country;
  }


  public void setCountry(String country) {
    this.country = country;
  }


  public CapiEvent region(String region) {
    
    this.region = region;
    return this;
  }

   /**
   * Get region
   * @return region
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getRegion() {
    return region;
  }


  public void setRegion(String region) {
    this.region = region;
  }


  public CapiEvent purchaseUserValue(String purchaseUserValue) {
    
    this.purchaseUserValue = purchaseUserValue;
    return this;
  }

   /**
   * Get purchaseUserValue
   * @return purchaseUserValue
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getPurchaseUserValue() {
    return purchaseUserValue;
  }


  public void setPurchaseUserValue(String purchaseUserValue) {
    this.purchaseUserValue = purchaseUserValue;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CapiEvent capiEvent = (CapiEvent) o;
    return Objects.equals(this.pixelId, capiEvent.pixelId) &&
        Objects.equals(this.appId, capiEvent.appId) &&
        Objects.equals(this.snapAppId, capiEvent.snapAppId) &&
        Objects.equals(this.eventType, capiEvent.eventType) &&
        Objects.equals(this.eventConversionType, capiEvent.eventConversionType) &&
        Objects.equals(this.eventTag, capiEvent.eventTag) &&
        Objects.equals(this.timestamp, capiEvent.timestamp) &&
        Objects.equals(this.hashedEmail, capiEvent.hashedEmail) &&
        Objects.equals(this.hashedMobileAdId, capiEvent.hashedMobileAdId) &&
        Objects.equals(this.uuidC1, capiEvent.uuidC1) &&
        Objects.equals(this.hashedIdfv, capiEvent.hashedIdfv) &&
        Objects.equals(this.hashedPhoneNumber, capiEvent.hashedPhoneNumber) &&
        Objects.equals(this.userAgent, capiEvent.userAgent) &&
        Objects.equals(this.hashedIpAddress, capiEvent.hashedIpAddress) &&
        Objects.equals(this.itemCategory, capiEvent.itemCategory) &&
        Objects.equals(this.itemIds, capiEvent.itemIds) &&
        Objects.equals(this.description, capiEvent.description) &&
        Objects.equals(this.numberItems, capiEvent.numberItems) &&
        Objects.equals(this.price, capiEvent.price) &&
        Objects.equals(this.currency, capiEvent.currency) &&
        Objects.equals(this.transactionId, capiEvent.transactionId) &&
        Objects.equals(this.level, capiEvent.level) &&
        Objects.equals(this.clientDedupId, capiEvent.clientDedupId) &&
        Objects.equals(this.dataUse, capiEvent.dataUse) &&
        Objects.equals(this.searchString, capiEvent.searchString) &&
        Objects.equals(this.pageUrl, capiEvent.pageUrl) &&
        Objects.equals(this.signUpMethod, capiEvent.signUpMethod) &&
        Objects.equals(this.hashedFirstNameSha, capiEvent.hashedFirstNameSha) &&
        Objects.equals(this.hashedFirstNameSdx, capiEvent.hashedFirstNameSdx) &&
        Objects.equals(this.hashedMiddleNameSha, capiEvent.hashedMiddleNameSha) &&
        Objects.equals(this.hashedMiddleNameSdx, capiEvent.hashedMiddleNameSdx) &&
        Objects.equals(this.hashedLastNameSha, capiEvent.hashedLastNameSha) &&
        Objects.equals(this.hashedLastNameSdx, capiEvent.hashedLastNameSdx) &&
        Objects.equals(this.hashedCitySha, capiEvent.hashedCitySha) &&
        Objects.equals(this.hashedCitySdx, capiEvent.hashedCitySdx) &&
        Objects.equals(this.hashedStateSha, capiEvent.hashedStateSha) &&
        Objects.equals(this.hashedStateSdx, capiEvent.hashedStateSdx) &&
        Objects.equals(this.hashedZip, capiEvent.hashedZip) &&
        Objects.equals(this.hashedDobMonth, capiEvent.hashedDobMonth) &&
        Objects.equals(this.hashedDobDay, capiEvent.hashedDobDay) &&
        Objects.equals(this.integration, capiEvent.integration) &&
        Objects.equals(this.clickId, capiEvent.clickId) &&
        Objects.equals(this.brands, capiEvent.brands) &&
        Objects.equals(this.country, capiEvent.country) &&
        Objects.equals(this.region, capiEvent.region) &&
        Objects.equals(this.purchaseUserValue, capiEvent.purchaseUserValue);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pixelId, appId, snapAppId, eventType, eventConversionType, eventTag, timestamp, hashedEmail, hashedMobileAdId, uuidC1, hashedIdfv, hashedPhoneNumber, userAgent, hashedIpAddress, itemCategory, itemIds, description, numberItems, price, currency, transactionId, level, clientDedupId, dataUse, searchString, pageUrl, signUpMethod, hashedFirstNameSha, hashedFirstNameSdx, hashedMiddleNameSha, hashedMiddleNameSdx, hashedLastNameSha, hashedLastNameSdx, hashedCitySha, hashedCitySdx, hashedStateSha, hashedStateSdx, hashedZip, hashedDobMonth, hashedDobDay, integration, clickId, brands, country, region, purchaseUserValue);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CapiEvent {\n");
    sb.append("    pixelId: ").append(toIndentedString(pixelId)).append("\n");
    sb.append("    appId: ").append(toIndentedString(appId)).append("\n");
    sb.append("    snapAppId: ").append(toIndentedString(snapAppId)).append("\n");
    sb.append("    eventType: ").append(toIndentedString(eventType)).append("\n");
    sb.append("    eventConversionType: ").append(toIndentedString(eventConversionType)).append("\n");
    sb.append("    eventTag: ").append(toIndentedString(eventTag)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("    hashedEmail: ").append(toIndentedString(hashedEmail)).append("\n");
    sb.append("    hashedMobileAdId: ").append(toIndentedString(hashedMobileAdId)).append("\n");
    sb.append("    uuidC1: ").append(toIndentedString(uuidC1)).append("\n");
    sb.append("    hashedIdfv: ").append(toIndentedString(hashedIdfv)).append("\n");
    sb.append("    hashedPhoneNumber: ").append(toIndentedString(hashedPhoneNumber)).append("\n");
    sb.append("    userAgent: ").append(toIndentedString(userAgent)).append("\n");
    sb.append("    hashedIpAddress: ").append(toIndentedString(hashedIpAddress)).append("\n");
    sb.append("    itemCategory: ").append(toIndentedString(itemCategory)).append("\n");
    sb.append("    itemIds: ").append(toIndentedString(itemIds)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    numberItems: ").append(toIndentedString(numberItems)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    transactionId: ").append(toIndentedString(transactionId)).append("\n");
    sb.append("    level: ").append(toIndentedString(level)).append("\n");
    sb.append("    clientDedupId: ").append(toIndentedString(clientDedupId)).append("\n");
    sb.append("    dataUse: ").append(toIndentedString(dataUse)).append("\n");
    sb.append("    searchString: ").append(toIndentedString(searchString)).append("\n");
    sb.append("    pageUrl: ").append(toIndentedString(pageUrl)).append("\n");
    sb.append("    signUpMethod: ").append(toIndentedString(signUpMethod)).append("\n");
    sb.append("    hashedFirstNameSha: ").append(toIndentedString(hashedFirstNameSha)).append("\n");
    sb.append("    hashedFirstNameSdx: ").append(toIndentedString(hashedFirstNameSdx)).append("\n");
    sb.append("    hashedMiddleNameSha: ").append(toIndentedString(hashedMiddleNameSha)).append("\n");
    sb.append("    hashedMiddleNameSdx: ").append(toIndentedString(hashedMiddleNameSdx)).append("\n");
    sb.append("    hashedLastNameSha: ").append(toIndentedString(hashedLastNameSha)).append("\n");
    sb.append("    hashedLastNameSdx: ").append(toIndentedString(hashedLastNameSdx)).append("\n");
    sb.append("    hashedCitySha: ").append(toIndentedString(hashedCitySha)).append("\n");
    sb.append("    hashedCitySdx: ").append(toIndentedString(hashedCitySdx)).append("\n");
    sb.append("    hashedStateSha: ").append(toIndentedString(hashedStateSha)).append("\n");
    sb.append("    hashedStateSdx: ").append(toIndentedString(hashedStateSdx)).append("\n");
    sb.append("    hashedZip: ").append(toIndentedString(hashedZip)).append("\n");
    sb.append("    hashedDobMonth: ").append(toIndentedString(hashedDobMonth)).append("\n");
    sb.append("    hashedDobDay: ").append(toIndentedString(hashedDobDay)).append("\n");
    sb.append("    integration: ").append(toIndentedString(integration)).append("\n");
    sb.append("    clickId: ").append(toIndentedString(clickId)).append("\n");
    sb.append("    brands: ").append(toIndentedString(brands)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    region: ").append(toIndentedString(region)).append("\n");
    sb.append("    purchaseUserValue: ").append(toIndentedString(purchaseUserValue)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("pixel_id");
    openapiFields.add("app_id");
    openapiFields.add("snap_app_id");
    openapiFields.add("event_type");
    openapiFields.add("event_conversion_type");
    openapiFields.add("event_tag");
    openapiFields.add("timestamp");
    openapiFields.add("hashed_email");
    openapiFields.add("hashed_mobile_ad_id");
    openapiFields.add("uuid_c1");
    openapiFields.add("hashed_idfv");
    openapiFields.add("hashed_phone_number");
    openapiFields.add("user_agent");
    openapiFields.add("hashed_ip_address");
    openapiFields.add("item_category");
    openapiFields.add("item_ids");
    openapiFields.add("description");
    openapiFields.add("number_items");
    openapiFields.add("price");
    openapiFields.add("currency");
    openapiFields.add("transaction_id");
    openapiFields.add("level");
    openapiFields.add("client_dedup_id");
    openapiFields.add("data_use");
    openapiFields.add("search_string");
    openapiFields.add("page_url");
    openapiFields.add("sign_up_method");
    openapiFields.add("hashed_first_name_sha");
    openapiFields.add("hashed_first_name_sdx");
    openapiFields.add("hashed_middle_name_sha");
    openapiFields.add("hashed_middle_name_sdx");
    openapiFields.add("hashed_last_name_sha");
    openapiFields.add("hashed_last_name_sdx");
    openapiFields.add("hashed_city_sha");
    openapiFields.add("hashed_city_sdx");
    openapiFields.add("hashed_state_sha");
    openapiFields.add("hashed_state_sdx");
    openapiFields.add("hashed_zip");
    openapiFields.add("hashed_dob_month");
    openapiFields.add("hashed_dob_day");
    openapiFields.add("integration");
    openapiFields.add("click_id");
    openapiFields.add("brands");
    openapiFields.add("country");
    openapiFields.add("region");
    openapiFields.add("purchase_user_value");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to CapiEvent
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (CapiEvent.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has required fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in CapiEvent is not found in the empty JSON string", CapiEvent.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!CapiEvent.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `CapiEvent` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      if (jsonObj.get("pixel_id") != null && !jsonObj.get("pixel_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `pixel_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("pixel_id").toString()));
      }
      if (jsonObj.get("app_id") != null && !jsonObj.get("app_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `app_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("app_id").toString()));
      }
      if (jsonObj.get("snap_app_id") != null && !jsonObj.get("snap_app_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `snap_app_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("snap_app_id").toString()));
      }
      if (jsonObj.get("event_type") != null && !jsonObj.get("event_type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `event_type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("event_type").toString()));
      }
      if (jsonObj.get("event_conversion_type") != null && !jsonObj.get("event_conversion_type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `event_conversion_type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("event_conversion_type").toString()));
      }
      if (jsonObj.get("event_tag") != null && !jsonObj.get("event_tag").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `event_tag` to be a primitive type in the JSON string but got `%s`", jsonObj.get("event_tag").toString()));
      }
      if (jsonObj.get("timestamp") != null && !jsonObj.get("timestamp").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `timestamp` to be a primitive type in the JSON string but got `%s`", jsonObj.get("timestamp").toString()));
      }
      if (jsonObj.get("hashed_email") != null && !jsonObj.get("hashed_email").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `hashed_email` to be a primitive type in the JSON string but got `%s`", jsonObj.get("hashed_email").toString()));
      }
      if (jsonObj.get("hashed_mobile_ad_id") != null && !jsonObj.get("hashed_mobile_ad_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `hashed_mobile_ad_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("hashed_mobile_ad_id").toString()));
      }
      if (jsonObj.get("uuid_c1") != null && !jsonObj.get("uuid_c1").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `uuid_c1` to be a primitive type in the JSON string but got `%s`", jsonObj.get("uuid_c1").toString()));
      }
      if (jsonObj.get("hashed_idfv") != null && !jsonObj.get("hashed_idfv").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `hashed_idfv` to be a primitive type in the JSON string but got `%s`", jsonObj.get("hashed_idfv").toString()));
      }
      if (jsonObj.get("hashed_phone_number") != null && !jsonObj.get("hashed_phone_number").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `hashed_phone_number` to be a primitive type in the JSON string but got `%s`", jsonObj.get("hashed_phone_number").toString()));
      }
      if (jsonObj.get("user_agent") != null && !jsonObj.get("user_agent").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `user_agent` to be a primitive type in the JSON string but got `%s`", jsonObj.get("user_agent").toString()));
      }
      if (jsonObj.get("hashed_ip_address") != null && !jsonObj.get("hashed_ip_address").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `hashed_ip_address` to be a primitive type in the JSON string but got `%s`", jsonObj.get("hashed_ip_address").toString()));
      }
      if (jsonObj.get("item_category") != null && !jsonObj.get("item_category").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `item_category` to be a primitive type in the JSON string but got `%s`", jsonObj.get("item_category").toString()));
      }
      if (jsonObj.get("item_ids") != null && !jsonObj.get("item_ids").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `item_ids` to be a primitive type in the JSON string but got `%s`", jsonObj.get("item_ids").toString()));
      }
      if (jsonObj.get("description") != null && !jsonObj.get("description").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `description` to be a primitive type in the JSON string but got `%s`", jsonObj.get("description").toString()));
      }
      if (jsonObj.get("number_items") != null && !jsonObj.get("number_items").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `number_items` to be a primitive type in the JSON string but got `%s`", jsonObj.get("number_items").toString()));
      }
      if (jsonObj.get("price") != null && !jsonObj.get("price").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `price` to be a primitive type in the JSON string but got `%s`", jsonObj.get("price").toString()));
      }
      if (jsonObj.get("currency") != null && !jsonObj.get("currency").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `currency` to be a primitive type in the JSON string but got `%s`", jsonObj.get("currency").toString()));
      }
      if (jsonObj.get("transaction_id") != null && !jsonObj.get("transaction_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `transaction_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("transaction_id").toString()));
      }
      if (jsonObj.get("level") != null && !jsonObj.get("level").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `level` to be a primitive type in the JSON string but got `%s`", jsonObj.get("level").toString()));
      }
      if (jsonObj.get("client_dedup_id") != null && !jsonObj.get("client_dedup_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `client_dedup_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("client_dedup_id").toString()));
      }
      if (jsonObj.get("data_use") != null && !jsonObj.get("data_use").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `data_use` to be a primitive type in the JSON string but got `%s`", jsonObj.get("data_use").toString()));
      }
      if (jsonObj.get("search_string") != null && !jsonObj.get("search_string").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `search_string` to be a primitive type in the JSON string but got `%s`", jsonObj.get("search_string").toString()));
      }
      if (jsonObj.get("page_url") != null && !jsonObj.get("page_url").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `page_url` to be a primitive type in the JSON string but got `%s`", jsonObj.get("page_url").toString()));
      }
      if (jsonObj.get("sign_up_method") != null && !jsonObj.get("sign_up_method").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `sign_up_method` to be a primitive type in the JSON string but got `%s`", jsonObj.get("sign_up_method").toString()));
      }
      if (jsonObj.get("hashed_first_name_sha") != null && !jsonObj.get("hashed_first_name_sha").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `hashed_first_name_sha` to be a primitive type in the JSON string but got `%s`", jsonObj.get("hashed_first_name_sha").toString()));
      }
      if (jsonObj.get("hashed_first_name_sdx") != null && !jsonObj.get("hashed_first_name_sdx").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `hashed_first_name_sdx` to be a primitive type in the JSON string but got `%s`", jsonObj.get("hashed_first_name_sdx").toString()));
      }
      if (jsonObj.get("hashed_middle_name_sha") != null && !jsonObj.get("hashed_middle_name_sha").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `hashed_middle_name_sha` to be a primitive type in the JSON string but got `%s`", jsonObj.get("hashed_middle_name_sha").toString()));
      }
      if (jsonObj.get("hashed_middle_name_sdx") != null && !jsonObj.get("hashed_middle_name_sdx").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `hashed_middle_name_sdx` to be a primitive type in the JSON string but got `%s`", jsonObj.get("hashed_middle_name_sdx").toString()));
      }
      if (jsonObj.get("hashed_last_name_sha") != null && !jsonObj.get("hashed_last_name_sha").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `hashed_last_name_sha` to be a primitive type in the JSON string but got `%s`", jsonObj.get("hashed_last_name_sha").toString()));
      }
      if (jsonObj.get("hashed_last_name_sdx") != null && !jsonObj.get("hashed_last_name_sdx").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `hashed_last_name_sdx` to be a primitive type in the JSON string but got `%s`", jsonObj.get("hashed_last_name_sdx").toString()));
      }
      if (jsonObj.get("hashed_city_sha") != null && !jsonObj.get("hashed_city_sha").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `hashed_city_sha` to be a primitive type in the JSON string but got `%s`", jsonObj.get("hashed_city_sha").toString()));
      }
      if (jsonObj.get("hashed_city_sdx") != null && !jsonObj.get("hashed_city_sdx").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `hashed_city_sdx` to be a primitive type in the JSON string but got `%s`", jsonObj.get("hashed_city_sdx").toString()));
      }
      if (jsonObj.get("hashed_state_sha") != null && !jsonObj.get("hashed_state_sha").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `hashed_state_sha` to be a primitive type in the JSON string but got `%s`", jsonObj.get("hashed_state_sha").toString()));
      }
      if (jsonObj.get("hashed_state_sdx") != null && !jsonObj.get("hashed_state_sdx").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `hashed_state_sdx` to be a primitive type in the JSON string but got `%s`", jsonObj.get("hashed_state_sdx").toString()));
      }
      if (jsonObj.get("hashed_zip") != null && !jsonObj.get("hashed_zip").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `hashed_zip` to be a primitive type in the JSON string but got `%s`", jsonObj.get("hashed_zip").toString()));
      }
      if (jsonObj.get("hashed_dob_month") != null && !jsonObj.get("hashed_dob_month").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `hashed_dob_month` to be a primitive type in the JSON string but got `%s`", jsonObj.get("hashed_dob_month").toString()));
      }
      if (jsonObj.get("hashed_dob_day") != null && !jsonObj.get("hashed_dob_day").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `hashed_dob_day` to be a primitive type in the JSON string but got `%s`", jsonObj.get("hashed_dob_day").toString()));
      }
      if (jsonObj.get("integration") != null && !jsonObj.get("integration").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `integration` to be a primitive type in the JSON string but got `%s`", jsonObj.get("integration").toString()));
      }
      if (jsonObj.get("click_id") != null && !jsonObj.get("click_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `click_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("click_id").toString()));
      }
      if (jsonObj.get("brands") != null && !jsonObj.get("brands").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `brands` to be a primitive type in the JSON string but got `%s`", jsonObj.get("brands").toString()));
      }
      if (jsonObj.get("country") != null && !jsonObj.get("country").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `country` to be a primitive type in the JSON string but got `%s`", jsonObj.get("country").toString()));
      }
      if (jsonObj.get("region") != null && !jsonObj.get("region").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `region` to be a primitive type in the JSON string but got `%s`", jsonObj.get("region").toString()));
      }
      if (jsonObj.get("purchase_user_value") != null && !jsonObj.get("purchase_user_value").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `purchase_user_value` to be a primitive type in the JSON string but got `%s`", jsonObj.get("purchase_user_value").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CapiEvent.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CapiEvent' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CapiEvent> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CapiEvent.class));

       return (TypeAdapter<T>) new TypeAdapter<CapiEvent>() {
           @Override
           public void write(JsonWriter out, CapiEvent value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CapiEvent read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of CapiEvent given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of CapiEvent
  * @throws IOException if the JSON string is invalid with respect to CapiEvent
  */
  public static CapiEvent fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CapiEvent.class);
  }

 /**
  * Convert an instance of CapiEvent to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

