/*
 * Snap Conversions API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.snap.business.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.snap.business.sdk.JSON;

/**
 * ResponseErrorRecords
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class ResponseErrorRecords {
  public static final String SERIALIZED_NAME_REASON = "reason";
  @SerializedName(SERIALIZED_NAME_REASON)
  private String reason;

  public static final String SERIALIZED_NAME_RECORD_INDEXES = "record_indexes";
  @SerializedName(SERIALIZED_NAME_RECORD_INDEXES)
  private List<Integer> recordIndexes = null;

  public ResponseErrorRecords() { 
  }

  public ResponseErrorRecords reason(String reason) {
    
    this.reason = reason;
    return this;
  }

   /**
   * Get reason
   * @return reason
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getReason() {
    return reason;
  }


  public void setReason(String reason) {
    this.reason = reason;
  }


  public ResponseErrorRecords recordIndexes(List<Integer> recordIndexes) {
    
    this.recordIndexes = recordIndexes;
    return this;
  }

  public ResponseErrorRecords addRecordIndexesItem(Integer recordIndexesItem) {
    if (this.recordIndexes == null) {
      this.recordIndexes = new ArrayList<>();
    }
    this.recordIndexes.add(recordIndexesItem);
    return this;
  }

   /**
   * Get recordIndexes
   * @return recordIndexes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<Integer> getRecordIndexes() {
    return recordIndexes;
  }


  public void setRecordIndexes(List<Integer> recordIndexes) {
    this.recordIndexes = recordIndexes;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseErrorRecords responseErrorRecords = (ResponseErrorRecords) o;
    return Objects.equals(this.reason, responseErrorRecords.reason) &&
        Objects.equals(this.recordIndexes, responseErrorRecords.recordIndexes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(reason, recordIndexes);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseErrorRecords {\n");
    sb.append("    reason: ").append(toIndentedString(reason)).append("\n");
    sb.append("    recordIndexes: ").append(toIndentedString(recordIndexes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("reason");
    openapiFields.add("record_indexes");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to ResponseErrorRecords
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (ResponseErrorRecords.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has required fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in ResponseErrorRecords is not found in the empty JSON string", ResponseErrorRecords.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!ResponseErrorRecords.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ResponseErrorRecords` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      if (jsonObj.get("reason") != null && !jsonObj.get("reason").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `reason` to be a primitive type in the JSON string but got `%s`", jsonObj.get("reason").toString()));
      }
      // ensure the json data is an array
      if (jsonObj.get("record_indexes") != null && !jsonObj.get("record_indexes").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `record_indexes` to be an array in the JSON string but got `%s`", jsonObj.get("record_indexes").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ResponseErrorRecords.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ResponseErrorRecords' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ResponseErrorRecords> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ResponseErrorRecords.class));

       return (TypeAdapter<T>) new TypeAdapter<ResponseErrorRecords>() {
           @Override
           public void write(JsonWriter out, ResponseErrorRecords value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ResponseErrorRecords read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ResponseErrorRecords given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ResponseErrorRecords
  * @throws IOException if the JSON string is invalid with respect to ResponseErrorRecords
  */
  public static ResponseErrorRecords fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ResponseErrorRecords.class);
  }

 /**
  * Convert an instance of ResponseErrorRecords to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

