/*
 * Snap Conversions API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.snap.business.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.snap.business.sdk.model.ValidatedFieldsItems;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.snap.business.sdk.JSON;

/**
 * ValidatedFields
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class ValidatedFields {
  public static final String SERIALIZED_NAME_VALIDATED_FIELDS = "validated_fields";
  @SerializedName(SERIALIZED_NAME_VALIDATED_FIELDS)
  private ValidatedFieldsItems validatedFields;

  public static final String SERIALIZED_NAME_RECORD_INDEX = "record_index";
  @SerializedName(SERIALIZED_NAME_RECORD_INDEX)
  private Integer recordIndex;

  public ValidatedFields() { 
  }

  public ValidatedFields validatedFields(ValidatedFieldsItems validatedFields) {
    
    this.validatedFields = validatedFields;
    return this;
  }

   /**
   * Get validatedFields
   * @return validatedFields
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ValidatedFieldsItems getValidatedFields() {
    return validatedFields;
  }


  public void setValidatedFields(ValidatedFieldsItems validatedFields) {
    this.validatedFields = validatedFields;
  }


  public ValidatedFields recordIndex(Integer recordIndex) {
    
    this.recordIndex = recordIndex;
    return this;
  }

   /**
   * Get recordIndex
   * @return recordIndex
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getRecordIndex() {
    return recordIndex;
  }


  public void setRecordIndex(Integer recordIndex) {
    this.recordIndex = recordIndex;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ValidatedFields validatedFields = (ValidatedFields) o;
    return Objects.equals(this.validatedFields, validatedFields.validatedFields) &&
        Objects.equals(this.recordIndex, validatedFields.recordIndex);
  }

  @Override
  public int hashCode() {
    return Objects.hash(validatedFields, recordIndex);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ValidatedFields {\n");
    sb.append("    validatedFields: ").append(toIndentedString(validatedFields)).append("\n");
    sb.append("    recordIndex: ").append(toIndentedString(recordIndex)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("validated_fields");
    openapiFields.add("record_index");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to ValidatedFields
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (ValidatedFields.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has required fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in ValidatedFields is not found in the empty JSON string", ValidatedFields.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!ValidatedFields.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ValidatedFields` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      // validate the optional field `validated_fields`
      if (jsonObj.getAsJsonObject("validated_fields") != null) {
        ValidatedFieldsItems.validateJsonObject(jsonObj.getAsJsonObject("validated_fields"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ValidatedFields.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ValidatedFields' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ValidatedFields> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ValidatedFields.class));

       return (TypeAdapter<T>) new TypeAdapter<ValidatedFields>() {
           @Override
           public void write(JsonWriter out, ValidatedFields value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ValidatedFields read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ValidatedFields given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ValidatedFields
  * @throws IOException if the JSON string is invalid with respect to ValidatedFields
  */
  public static ValidatedFields fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ValidatedFields.class);
  }

 /**
  * Convert an instance of ValidatedFields to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

